import { Schema, Types, model } from "mongoose";
import { Minecraft } from "../../types/minecraft";

const MinecraftSchema = new Schema<Minecraft>({
  mojangCacheUntil: Date,
  hypixelCacheUntil: Date,
  uuid: {
    type: String,
    required: true,
    unique: true,
  },
  username: String,
  skin: {
    url: String,
    id: String,
  },
  cape: {
    url: String,
    id: String,
  },
  newPackageRank: String,
  monthlyPackageRank: String,
  rankPlusColor: String,
  monthlyRankColor: String,
  rank: String,
  prefix: String,
  firstLogin: Number,
  lastLogin: Number,
  achievementPoints: Number,
  totalRewards: Number,
  totalDailyRewards: Number,
  rewardStreak: Number,
  rewardScore: Number,
  level: Number,
  expToNextLevel: Number,
  levelExpFloor: Number,
  levelProgress: Number,
  games: {
    tntGames: {
      wins: Number,
      winstreak: Number,
      coins: Number,
      particleEffect: String,
      deathEffect: String,
      voidMessage: String,
      hat: String,
      doubleJumpEffect: String,
      playtime: String,
      settings: {
        wizardsActionBar: String,
        runActionBar: String,
        tagActionBar: String,
        tipHolograms: String,
        wizardsCooldownMessages: String,
        doubleJumpFeather: String,
        wizardsPrestigeParticles: String,
      },
      modes: {
        bowSpleef: {
          wins: Number,
          deaths: Number,
          shotsLanded: Number,
          winLossRatio: Number,
          shotsGameRatio: Number,
        },
        tntRun: {
          wins: Number,
          deaths: Number,
          record: String,
          winLossRatio: Number,
          blocksRan: Number,
          potionsLanded: Number,
        },
        pvpRun: {
          wins: Number,
          kills: Number,
          deaths: Number,
          record: String,
          winLossRatio: Number,
          killDeathRatio: Number,
          killGameRatio: Number,
        },
        tntTag: {
          wins: Number,
          kills: Number,
          deaths: Number,
          tags: Number,
          tagKillRatio: Number,
          killWinRatio: Number,
          winLossRatio: Number,
        },
        wizards: {
          wins: Number,
          kills: Number,
          deaths: Number,
          assists: Number,
          classes: Array,
        },
      },
    },
  },
});

export const MinecraftModel = model<Minecraft>("Minecraft", MinecraftSchema);
